# Site settings
title:          牧原村音公式オフィシャルサイト
description:    "牧原村音公式オフィシャルサイト"
url:            "https://chenhn1971.github.io/muraonsite"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         エンフー
  url:          
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# Multilanguage
languages: ["ja", "en", "zh_CN"]
default_lang: "ja"
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "assets", "_sass", "_layouts", "_includes"]
parallel_localization: true
url: https://counta.github.io/muraonsite

- name: Jekyll Deploy Action
  uses: jeffreytse/jekyll-deploy-action@v0.6.0
